version: '3.8'

services:
  graphrag-app:
    build:
      context: .
      dockerfile: Dockerfile.light
    container_name: graphrag-intelligent-assistant-light
    ports:
      - "8501:8501"
    volumes:
      # 最小化 volume 掛載
      - .:/app
      - /app/data                  # 排除宿主機的 data 目錄
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge