version: '3.8'

services:
  graphrag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphrag-intelligent-assistant
    ports:
      - "8501:8501"
    volumes:
      # 掛載整個應用程式代碼 (開發模式)
      - .:/app                     # 掛載整個專案目錄
      - /app/data                  # 排除 data 目錄 (使用容器內版本)
      - ./data:/app/data           # 重新掛載 data 目錄 (持久化)
      - ./.env:/app/.env           # 掛載環境變數檔案
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Elasticsearch 配置
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ENABLE_ELASTICSEARCH=true
      - RAG_SYSTEM_TYPE=enhanced
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - rag-network

  # Elasticsearch 向量資料庫 (替代 ChromaDB)
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: rag-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
